name: Manual Build Android

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish the build (e.g., v2.0.1)'
        required: true
      godot_version:
        description: 'Godot version to be builded (e.g., 3.5)'
        required: true
      build_version:
        description: 'The Build Version of Godot (stable/rc1/beta1) (`alpha` or pre-alpha` could not work).'
        default: 'stable'

jobs:
  android-template:
    name: Compiling Gradle (Android)
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    
    - name: Verify current inputs godot_version
      run: |
        CURRENT_GODOT_VERSION=${{ github.event.inputs.godot_version }}
        if [ ${#CURRENT_GODOT_VERSION} -eq 1 ]; then CURRENT_GODOT_VERSION="${CURRENT_GODOT_VERSION}.0"; fi
        echo "CURRENT_GODOT_VERSION=${CURRENT_GODOT_VERSION}" >> $GITHUB_ENV

    - name: Download and prepare the Stable Godot .AAR LIB
      run: |
        chmod +x ./scripts/unix/download_godot.sh
        ./scripts/unix/download_godot.sh ${{env.CURRENT_GODOT_VERSION}} ${{ github.event.inputs.build_version }}

    - name: Build Plugins
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Compress the artifact output
      run: |
        ./gradlew zipPlugins -PgodotVersion="${{env.CURRENT_GODOT_VERSION}}"
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .output/poing-godot-admob-android-v${{env.CURRENT_GODOT_VERSION}}.zip
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
